"""initial schema - policy_chunks and policy_meta

Revision ID: 4536f57473af
Revises:
Create Date: 2026-08-05 11:09:13.928873

"""

from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4536f57473af"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_chunks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("chunk_type", sa.String(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False
        ),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("section", sa.String(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_policy_chunks_agent_hash",
        "policy_chunks",
        ["agent_id", "policy_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_chunks_agent_id"), "policy_chunks", ["agent_id"], unique=False
    )

    # ── Custom indexes (not expressible via ORM autogenerate) ──────────────────

    # pgvector HNSW index for fast cosine similarity search on embeddings.
    op.execute("""
        CREATE INDEX policy_chunks_embedding_idx
        ON policy_chunks USING hnsw (embedding vector_cosine_ops)
    """)

    # pg_textsearch BM25 index for keyword search on chunk text.
    op.execute("""
        CREATE INDEX policy_chunks_bm25_idx
        ON policy_chunks USING bm25 (chunk_text)
        WITH (text_config='english')
    """)

    op.create_table(
        "policy_meta",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("encoder_model", sa.String(), nullable=False),
        sa.Column("nli_model", sa.String(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("agent_id"),
        sa.UniqueConstraint("agent_id", name="uq_policy_meta_agent_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("policy_meta")
    op.drop_index("policy_chunks_bm25_idx", table_name="policy_chunks")
    op.drop_index("policy_chunks_embedding_idx", table_name="policy_chunks")
    op.drop_index(op.f("ix_policy_chunks_agent_id"), table_name="policy_chunks")
    op.drop_index("ix_policy_chunks_agent_hash", table_name="policy_chunks")
    op.drop_table("policy_chunks")
    # ### end Alembic commands ###
